project_id = "emscbdwqqnvcjskrdmzp"

[functions.fetch-stock-data]
verify_jwt = false

[functions.refresh-stock-data]
verify_jwt = false

[functions.stock-chart]
verify_jwt = false

[functions.stock-analysis]
verify_jwt = false
